name: Java Postgres CI

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed
env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  build:
    if: github.event.pull_request.merged == true
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Start PostgreSQL
        run: |
          sudo systemctl start postgresql.service
          pg_isready
      - name: Create junit user
        run: |
          sudo -u postgres psql --command="CREATE USER junit_user PASSWORD 'junit_password'"
      - name: Create junit database
        run: |
          sudo -u postgres createdb --owner=junit_user junit_database
          PGPASSWORD="junit_password" psql --username=junit_user --host=localhost --list junit_database
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: '**/*.jar'
        if: startsWith(github.ref, 'refs/tags/') && github.event.pull_request.merged == true
  ignore:
    if: github.event.pull_request.merged != true
    name: Ignoring closed pull request without merge
    runs-on: ubuntu-latest
    steps:
      - run : echo "Ignoring closed PR because it was not merged"